/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NameGUI.java
 *
 * Created on Apr 26, 2011, 2:56:50 PM
 */

package nameapp;

/**
 *
 * @author vcchavez
 */
public class NameGUI extends javax.swing.JFrame {

    /** Creates new form NameGUI */
    public NameGUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nameLabel = new javax.swing.JLabel();
        firstLabel = new javax.swing.JLabel();
        LastLabel = new javax.swing.JLabel();
        reformattedLabel = new javax.swing.JLabel();
        backwardsLabel = new javax.swing.JLabel();
        firstField = new javax.swing.JTextField();
        lastField = new javax.swing.JTextField();
        reformattedField = new javax.swing.JTextField();
        backwardsField = new javax.swing.JTextField();
        reformatButton = new javax.swing.JButton();
        backwardButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Name Formatter v1.0");

        nameLabel.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        nameLabel.setText("Name Formatter");

        firstLabel.setFont(new java.awt.Font("Vivaldi", 0, 18)); // NOI18N
        firstLabel.setText("First Name: ");

        LastLabel.setFont(new java.awt.Font("Vivaldi", 0, 18)); // NOI18N
        LastLabel.setText("Last Name:");

        reformattedLabel.setFont(new java.awt.Font("Vivaldi", 0, 18)); // NOI18N
        reformattedLabel.setText("Reformatted:");

        backwardsLabel.setFont(new java.awt.Font("Vivaldi", 0, 18)); // NOI18N
        backwardsLabel.setText("Backwards:");

        firstField.setToolTipText("Enter first name");
        firstField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstFieldActionPerformed(evt);
            }
        });

        lastField.setToolTipText("Enter last name");

        reformattedField.setToolTipText("LastName, FirstName");

        backwardsField.setToolTipText("Name spelled backwards");

        reformatButton.setText("Reformat");
        reformatButton.setToolTipText("Click to reformat");
        reformatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reformatButtonActionPerformed(evt);
            }
        });

        backwardButton.setText("Backward");
        backwardButton.setToolTipText("Click to spell name backwards");
        backwardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backwardButtonActionPerformed(evt);
            }
        });

        resetButton.setText("Reset");
        resetButton.setToolTipText("Click to reset form");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(firstLabel)
                            .addComponent(LastLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(reformattedLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(backwardsField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                    .addComponent(reformattedField, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lastField, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(firstField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
                                    .addComponent(backwardsLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))))
                .addContainerGap(87, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(reformatButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, Short.MAX_VALUE)
                .addGap(48, 48, 48)
                .addComponent(backwardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, Short.MAX_VALUE)
                .addGap(50, 50, 50)
                .addComponent(resetButton, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(nameLabel)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(firstLabel)
                    .addComponent(firstField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastLabel)
                    .addComponent(lastField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(reformattedLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backwardsLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(reformattedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(backwardsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reformatButton)
                    .addComponent(resetButton)
                    .addComponent(backwardButton))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstFieldActionPerformed

    private void reformatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reformatButtonActionPerformed
        // TODO add your handling code here:
        // get first name from firstField
        String fName = firstField.getText();
        String lName = lastField.getText();

        //create name object
        Name nm = new Name (fName, lName);

        //invoke reformat method
        String rename = nm.reformat();

        reformattedField.setText(rename);
    }//GEN-LAST:event_reformatButtonActionPerformed

    private void backwardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backwardButtonActionPerformed
        // TODO add your handling code here:
         String fName = firstField.getText();
        String lName = lastField.getText();

        //create name object
        Name nm = new Name (fName, lName);
        backwardsField.setText(nm.reverse());
    }//GEN-LAST:event_backwardButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        firstField.setText(null);
        lastField.setText(null);
        reformattedField.setText(null);
        backwardsField.setText(null);
    }//GEN-LAST:event_resetButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NameGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LastLabel;
    private javax.swing.JButton backwardButton;
    private javax.swing.JTextField backwardsField;
    private javax.swing.JLabel backwardsLabel;
    private javax.swing.JTextField firstField;
    private javax.swing.JLabel firstLabel;
    private javax.swing.JTextField lastField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JButton reformatButton;
    private javax.swing.JTextField reformattedField;
    private javax.swing.JLabel reformattedLabel;
    private javax.swing.JButton resetButton;
    // End of variables declaration//GEN-END:variables

}
