/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * teleGUI.java
 *
 * Created on May 16, 2011, 8:22:46 AM
 */

package teleconverter;

/**
 *
 * @author DGYanek
 */
public class teleGUI extends javax.swing.JFrame {

    /** Creates new form teleGUI */
    public teleGUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        areaField = new javax.swing.JTextField();
        areaLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        prefixField = new javax.swing.JTextField();
        prefixLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numField = new javax.swing.JTextField();
        numLabel = new javax.swing.JLabel();
        processButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 0, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Phone Number Converter");
        jLabel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 263, 30));

        areaField.setFont(new java.awt.Font("Arial Narrow", 0, 18));
        areaField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(areaField, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 48, 50, 30));

        areaLabel.setFont(new java.awt.Font("Calibri", 0, 12));
        areaLabel.setText("area code");
        getContentPane().add(areaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 78, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel1.setText("-");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 10, 30));

        prefixField.setFont(new java.awt.Font("Arial Narrow", 0, 18));
        prefixField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(prefixField, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 50, 30));

        prefixLabel.setFont(new java.awt.Font("Calibri", 0, 12));
        prefixLabel.setText("prefix");
        getContentPane().add(prefixLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24));
        jLabel2.setText("-");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        numField.setFont(new java.awt.Font("Arial Narrow", 0, 18));
        numField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(numField, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 90, 30));

        numLabel.setFont(new java.awt.Font("Calibri", 0, 12));
        numLabel.setText("phone #");
        getContentPane().add(numLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 80, -1, -1));

        processButton.setText("convert");
        processButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                processButtonActionPerformed(evt);
            }
        });
        getContentPane().add(processButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 100, -1));

        resetButton.setText("reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        getContentPane().add(resetButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 70, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void processButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_processButtonActionPerformed
        // TODO add your handling code here:
        String area = areaField.getText();
        String prefix = prefixField.getText();
        String num = numField.getText();

        String output="";

        TeleConverter tc = new TeleConverter(area, prefix, num);

        output = tc.convert();
        
        areaField.setText(output.substring(1,4));
        prefixField.setText(output.substring(5,8));
        numField.setText(output.substring(9));
}//GEN-LAST:event_processButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        areaField.setText("");
        prefixField.setText("");
        numField.setText("");
        areaField.grabFocus();
}//GEN-LAST:event_resetButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new teleGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField areaField;
    private javax.swing.JLabel areaLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField numField;
    private javax.swing.JLabel numLabel;
    private javax.swing.JTextField prefixField;
    private javax.swing.JLabel prefixLabel;
    private javax.swing.JButton processButton;
    private javax.swing.JButton resetButton;
    // End of variables declaration//GEN-END:variables

}
