/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * SlopeGUI.java
 *
 * Created on May 3, 2011, 9:36:14 AM
 */

package slopecalc;

/**
 *
 * @author vcchavez
 */
public class SlopeGUI extends javax.swing.JFrame {

    /** Creates new form SlopeGUI */
    public SlopeGUI() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        titleLabel = new javax.swing.JLabel();
        pt1Label = new javax.swing.JLabel();
        commaLabel = new javax.swing.JLabel();
        parenthLabel1 = new javax.swing.JLabel();
        point2label = new javax.swing.JLabel();
        commalabel2 = new javax.swing.JLabel();
        rParenthLabel2 = new javax.swing.JLabel();
        mLabel = new javax.swing.JLabel();
        distanceLabel = new javax.swing.JLabel();
        x1Field = new javax.swing.JTextField();
        y1Field = new javax.swing.JTextField();
        x2Field = new javax.swing.JTextField();
        y2Field = new javax.swing.JTextField();
        mField = new javax.swing.JTextField();
        distanceField = new javax.swing.JTextField();
        solutionButton = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        titleLabel.setFont(new java.awt.Font("Calibri", 0, 24));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("Slope Calulator");
        titleLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 51)));

        pt1Label.setFont(new java.awt.Font("Calibri", 0, 24));
        pt1Label.setText("point 1:  (");

        commaLabel.setFont(new java.awt.Font("Calibri", 0, 24));
        commaLabel.setText(",");

        parenthLabel1.setFont(new java.awt.Font("Calibri", 0, 24));
        parenthLabel1.setText(")");

        point2label.setFont(new java.awt.Font("Calibri", 0, 24));
        point2label.setText("point 2:  (");

        commalabel2.setFont(new java.awt.Font("Calibri", 0, 24));
        commalabel2.setText(",");

        rParenthLabel2.setFont(new java.awt.Font("Calibri", 0, 24));
        rParenthLabel2.setText(")");

        mLabel.setFont(new java.awt.Font("Calibri", 0, 24));
        mLabel.setText("m = ");

        distanceLabel.setFont(new java.awt.Font("Calibri", 0, 24));
        distanceLabel.setText("distance = ");

        x1Field.setFont(new java.awt.Font("Calibri", 0, 24));
        x1Field.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        y1Field.setFont(new java.awt.Font("Calibri", 0, 24));
        y1Field.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        x2Field.setFont(new java.awt.Font("Calibri", 0, 24));
        x2Field.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        y2Field.setFont(new java.awt.Font("Calibri", 0, 24));
        y2Field.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        mField.setFont(new java.awt.Font("Calibri", 0, 24));
        mField.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        distanceField.setFont(new java.awt.Font("Calibri", 0, 24));

        solutionButton.setFont(new java.awt.Font("Calibri", 0, 18));
        solutionButton.setText("solve");
        solutionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solutionButtonActionPerformed(evt);
            }
        });

        resetButton.setFont(new java.awt.Font("Calibri", 0, 18));
        resetButton.setText("reset");
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pt1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(x1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(commaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(y1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(parenthLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(mLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(distanceLabel)
                            .addComponent(solutionButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(resetButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38))
                            .addComponent(distanceField, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(point2label, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(x2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(commalabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(y2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(rParenthLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(titleLabel)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pt1Label)
                    .addComponent(x1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(commaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(y1Field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(parenthLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(point2label)
                        .addComponent(x2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(commalabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rParenthLabel2)
                        .addComponent(y2Field, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mLabel)
                    .addComponent(mField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(distanceLabel)
                    .addComponent(distanceField, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(solutionButton)
                    .addComponent(resetButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void solutionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solutionButtonActionPerformed
        // TODO add your handling code here:
        String x1Str = x1Field.getText();
        String y1Str = y1Field.getText();
        String x2Str = x2Field.getText();
        String y2Str = y2Field.getText();

        int x1 = Integer.parseInt(x1Str);
        int y1 = Integer.parseInt(y1Str);
        int x2 = Integer.parseInt(x2Str);
        int y2 = Integer.parseInt(y2Str);

        Line ln = new Line(x1, y1, x2, y2);
        double m = ln.getSlope();
        mField.setText("" + m);

        double dist = ln.getDistance();
        distanceField.setText("" + dist);

    }//GEN-LAST:event_solutionButtonActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        mField.setText(null);
        distanceField.setText(null);
        x1Field.setText(null);
        x2Field.setText(null);
        y1Field.setText(null);
        y2Field.setText(null);
    }//GEN-LAST:event_resetButtonActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SlopeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel commaLabel;
    private javax.swing.JLabel commalabel2;
    private javax.swing.JTextField distanceField;
    private javax.swing.JLabel distanceLabel;
    private javax.swing.JTextField mField;
    private javax.swing.JLabel mLabel;
    private javax.swing.JLabel parenthLabel1;
    private javax.swing.JLabel point2label;
    private javax.swing.JLabel pt1Label;
    private javax.swing.JLabel rParenthLabel2;
    private javax.swing.JButton resetButton;
    private javax.swing.JButton solutionButton;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JTextField x1Field;
    private javax.swing.JTextField x2Field;
    private javax.swing.JTextField y1Field;
    private javax.swing.JTextField y2Field;
    // End of variables declaration//GEN-END:variables

}
